fantasylol/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from fantasylol import settings
from league import views
from league.views import log_in
from django.conf.urls.static import static

urlpatterns = [
    path("api/draft-players/", views.draft_players, name="draftplayers"),
    path("team/user/", views.user_team, name="userteam"),
    path("accounts/profile/", views.profile, name="profilepage"),
    path("", views.index, name="homepage"),
    path("accounts/login/", views.log_in, name="login"),
    path("admin/", admin.site.urls),
    path("accounts/signup/", views.signup, name="signup"),
    path("accounts/", include("django.contrib.auth.urls")),
    path("team/new/", views.team_creation, name="newteam"),
    path("team/draft/", views.draft, name="draft"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

league/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class LolTeam(models.Model):
    name = models.CharField(max_length=30)
    photo = models.ImageField(upload_to="lolteam")

    def __str__(self) -> str:
        return self.name


class Player(models.Model):
    TOP = "TP"
    JUNGLE = "JG"
    MID = "MD"
    ADC = "AD"
    SUPPORT = "SP"
    POSITION_CHOICES = [
        (TOP, "Top"),
        (JUNGLE, "Jungle"),
        (MID, "Mid"),
        (ADC, "ADC"),
        (SUPPORT, "Support"),
    ]
    name = models.CharField(max_length=30)
    lol_team = models.ForeignKey(LolTeam, on_delete=models.DO_NOTHING)
    photo = models.ImageField(upload_to="player")
    position = models.CharField(
        max_length=2,
        choices=POSITION_CHOICES,
    )

    def __str__(self) -> str:
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=30, unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    players = models.ManyToManyField(Player)

    def __str__(self) -> str:
        return self.name


class Statistics(models.Model):
    kills = models.IntegerField()
    deaths = models.IntegerField()
    assists = models.IntegerField()
    turrets = models.IntegerField()
    inhibitors = models.IntegerField()
    dragonKills = models.IntegerField()
    baronKills = models.IntegerField()

    def __str__(self) -> str:
        return self.name


class Game(models.Model):
    teamOne = models.CharField(max_length=30)
    teamTwo = models.CharField(max_length=30)
    teamOneScore = models.IntegerField()
    teamTwoScore = models.IntegerField()
    teamOneStats = Statistics
    teamTwoStats = Statistics

    def __str__(self) -> str:
        return self.name


class Week(models.Model):
    gameOne = Game
    gameTwo = Game
    gameThree = Game
    gameFour = Game
    gameFive = Game
    gameSix = Game
    gameSeven = Game
    gameEight = Game
    gameNine = Game
    gameTen = Game

    def __str__(self) -> str:
        return self.name


class Season(models.Model):
    weekOne = Week
    weekTwo = Week
    weekThree = Week
    weekFour = Week
    weekFive = Week
    weekSix = Week
    weekSeven = Week
    weekEight = Week

    def __str__(self) -> str:
        return self.name

league/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, User, AuthenticationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
import json

from league.models import Player, Team


# Create your views here.
def signup(request):
    message = ""
    if request.user.is_authenticated:
        return redirect("/")
    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            print("form is valid")
            user = form.save()
            login(request, user)
            return redirect("/")
        else:
            message = form.errors
    else:
        form = UserCreationForm()

    context = {"form": form, "message": message}
    return render(request, "league/signup.html", context)


def log_in(request):
    message = ""
    if request.user.is_authenticated:
        return redirect("/")
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            print("form is valid")
            user = form.get_user()
            login(request, user)
            nextRoute = request.GET.get("next", "/")
            return redirect(nextRoute)
        else:
            message = form.errors
    else:
        form = AuthenticationForm()

    context = {"form": form, "message": message}
    return render(request, "league/login.html", context)


def index(request):
    return render(request, "league/index.html")


@login_required
def profile(request):
    team = Team.objects.get(owner=request.user)
    context = {"team": team}
    return render(request, "league/profile.html", context)


@login_required
def team_creation(request):
    userTeams = Team.objects.filter(owner=request.user)
    if len(userTeams) > 0:
        return redirect("/team")
    userTeamName = request.GET.get("team-name", "")
    if not userTeamName:
        return render(request, "league/teamcreation.html")
    else:
        try:
            team = Team(name=userTeamName, owner=request.user)
            team.save()
            return redirect("/team/draft")
        except:
            context = {"error_message": "Team name is already taken"}
            return render(request, "league/teamcreation.html", context)


@login_required
def draft(request):
    userTeam = Team.objects.get(owner=request.user)
    players = Player.objects.all()
    context = {"players": players, "userTeam": userTeam}
    return render(request, "league/draft.html", context)


@login_required
def user_team(request):
    userTeams = Team.objects.get(owner=request.user)
    userPlayers = userTeams.players.all()

    context = {"userTeams": userTeams, "userPlayers": userPlayers}
    return render(request, "league/userteam.html", context)


@csrf_exempt
@login_required
def draft_players(request):
    if request.method == "POST":
        try:
            data = json.loads(request.body)
            selected_player_ids = data.get("selectedPlayerIDs", [])
            userTeam = Team.objects.get(owner=request.user)
            for playerId in selected_player_ids:
                userTeam.players.add(playerId)
            userTeam.save()
            if userTeam != 0:
                return JsonResponse(
                    {"message": "Players added to the team successfully"}
                )
        except json.JSONDecodeError:
            return JsonResponse({"error": "Invalid JSON data"}, status=400)

    return JsonResponse({"error": "Invalid request method"}, status=405)

league/templates/league/base.html
{% load static%}

<!doctype html>
<html lang="en" data-theme="dark">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'league/css/pico/pico.min.css' %}">
    <link rel="stylesheet" href="{% static 'league/css/main.css' %}">

    <title>League App</title>
    <script src="{% static '/league/scripts/index.js' %}" defer></script>
    {% block header %}
    {% endblock %}


</head>

<body>
    <nav class="nav">
        <ul>
            <li><a href="/"><strong>FL</strong></a></li>
        </ul>
        <ul>
            {% if request.user.is_authenticated %}
            <li><a href="/accounts/profile">{{user}} is active</a></li>
            <li><a href="/team/new">Create Team</a></li>
            {% else %}
            <li><a href="/accounts/signup">SignUp</a></li>
            <li><a href="/accounts/login">Log In</a></li>
            {% endif %}
        </ul>
    </nav>
    <main class="container">
        {% block container %}
        {% endblock %}
    </main>

</body>

</html>

league/templates/league/draft.html
{% extends "league/base.html" %}
{% load static %}


{% block container %}
<h1 id="title">Team Draft</h1>

<div class="grid">
    <div>
        <h2>Your Players</h2>

        <ul id="selectedplayers">

        </ul>
        <button id="submit-button">Submit</button>

    </div>
    <div>
        <h2>Available Players</h2>

        <ul class="draftlist" id="draftlist">
            {% for player in players %}
            <li id="{{player.id}}" class="player">{{player.name}}

                <span class="badge"
                    style="background-color: var(--{{player.position}}-color);">{{player.get_position_display}}</span>
                <button role="button" type="button" class="outline draftbutton"
                    onclick="selectPlayer('{{player.id}}')">Draft</button>
            </li>

            {% endfor %}
        </ul>
    </div>


</div>
{% endblock %}

league/templates/league/index.html
{% extends "league/base.html" %}
{% load static %}

{% block container %}
<h1 id="title">Welcome to Fantasy League!</h1>

{% endblock %}

league/templates/league/login.html
{% extends "league/base.html" %}
{% load static %}

{% block container %}
<h1>Welcome, Sign In!</h1>
<article class="grid">
    <img src="https://images.unsplash.com/photo-1587095951604-b9d924a3fda0" />
    <form method="post">
        {{message}}
        {% csrf_token %}
        {{form}}
        <button type="submit">Sign In</button>
    </form>
</article>
{% endblock %}

league/templates/league/loginfail.html
<h1>Failed</h1>

league/templates/league/profile.html
{% extends "league/base.html" %}
{% load static %}

{% block container %}
<h1>Your Profile</h1>
<article>
    <header>Team</header>
    <h2><a href="/team/user">{{team.name}}</a></h2>
</article>
{% endblock %}

league/templates/league/signup.html
{% extends "league/base.html" %}
{% load static %}

{% block container %}
<h1>SignUp</h1>
<article class="grid">
    <img src="https://images.unsplash.com/photo-1587095951604-b9d924a3fda0" />
    <form method="post">
        {{message}}
        {% csrf_token %}
        {{form}}
        <button type="submit">Register</button>
    </form>
</article>
{% endblock %}

league/templates/league/sucesslogin.html
<h1>Login Successful!</h1>

league/templates/league/teamcreation.html
{% extends "league/base.html" %}
{% load static %}

{% block container%}
<form action="" method="get">
    <div>
        <label for="team-name">Enter your Team name: </label>

        {% if error_message %}
        <input type="text" name="team-name" id="team-name" aria-invalid="true" required />
        <small class="errorMessage">{{error_message}}</small>
        {% else %}
        <input type="text" name="team-name" id="team-name" required />
        {%endif %}

    </div>
    <input type="submit" value="Create Team" />

</form>
{%endblock%}

league/templates/league/userteam.html
{% extends "league/base.html" %}
{% load static %}

{% block container %}
<h1>{{userTeams}}</h1>
<div>
    {% for player in userPlayers %}
    <ul>
        <li>{{player}}</li>
    </ul>
    {% endfor %}
</div>
{% endblock %}